---
name: Text-Lorem-More
version: 0.12
author:
  - Robert Krimen <robertkrimen@gmail.com>
abstract: Generate formatted nonsense using random Latin words.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Parse::RecDescent: 0
build_requires:
  Test::More: 0
provides:
  Text::Lorem::More:
    file: lib/Text/Lorem/More.pm
    version: 0.12
  Text::Lorem::More::Source:
    file: lib/Text/Lorem/More/Source.pm
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
